// @ts-ignore Generated by `opennextjs-cloudflare build`.
import nextWorker from "./.open-next/worker.js";
// @ts-ignore Generated by `opennextjs-cloudflare build`.
import { runWithCloudflareRequestContext } from "./.open-next/cloudflare/init.js";
import {
  DurableObject,
  WorkflowEntrypoint,
  type WorkflowEvent,
  type WorkflowStep,
} from "cloudflare:workers";

import { ingestionJobSchema, type IngestionJob } from "./src/lib/jobs/ingestion";
import {
  conversationRealtimeEventSchema,
  type ConversationRealtimeEvent,
} from "./src/lib/realtime/events";

async function processIngestionBatch(
  batch: MessageBatch<IngestionJob>,
  env: CloudflareEnv,
  _ctx: ExecutionContext,
) {
  for (const message of batch.messages) {
    try {
      const job = ingestionJobSchema.parse(message.body);
      const digest = await crypto.subtle.digest(
        "SHA-256",
        new TextEncoder().encode(job.idempotencyKey),
      );
      const workflowId = Array.from(new Uint8Array(digest), (byte) =>
        byte.toString(16).padStart(2, "0"),
      ).join("");
      await env.SOURCE_SYNC_WORKFLOW.create({ id: workflowId, params: job });
      message.ack();
    } catch (error) {
      const retryDelay = Math.min(30 * 2 ** message.attempts, 43_200);
      console.error(
        JSON.stringify({
          event: "ingestion.failed",
          messageId: message.id,
          attempt: message.attempts,
          error: error instanceof Error ? error.message : "Unknown ingestion error",
        }),
      );
      message.retry({ delaySeconds: retryDelay });
    }
  }
}

export class SourceSyncWorkflow extends WorkflowEntrypoint<CloudflareEnv, IngestionJob> {
  async run(event: Readonly<WorkflowEvent<IngestionJob>>, step: WorkflowStep) {
    const job = ingestionJobSchema.parse(event.payload);
    await step.do(
      "extract, chunk, and index source",
      {
        retries: { limit: 4, delay: "30 seconds", backoff: "exponential" },
        timeout: "10 minutes",
      },
      async () => {
        await runWithCloudflareRequestContext(
          new Request("https://widget.internal/workflows/source-sync"),
          this.env,
          this.ctx,
          async () => {
            const [{ getDb }, { processIngestionJob }] = await Promise.all([
              import("./src/lib/db/client"),
              import("./src/lib/jobs/ingestion"),
            ]);
            await processIngestionJob(getDb(), job);
            return new Response(null, { status: 204 });
          },
        );
        return { documentId: job.documentId };
      },
    );
    return { documentId: job.documentId, status: "COMPLETED" };
  }
}

export class ConversationRoom extends DurableObject<CloudflareEnv> {
  async fetch(request: Request) {
    if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") {
      return new Response("WebSocket upgrade required", { status: 426 });
    }
    const pair = new WebSocketPair();
    this.ctx.acceptWebSocket(pair[1]);
    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  broadcast(input: ConversationRealtimeEvent) {
    const event = conversationRealtimeEventSchema.parse(input);
    const payload = JSON.stringify(event);
    const sockets = this.ctx.getWebSockets();
    for (const socket of sockets) socket.send(payload);
    return sockets.length;
  }

  async webSocketMessage(socket: WebSocket, message: string | ArrayBuffer) {
    if (typeof message !== "string") return;
    let decoded: unknown;
    try {
      decoded = JSON.parse(message) as unknown;
    } catch {
      return;
    }
    const parsed = conversationRealtimeEventSchema.safeParse(decoded);
    if (!parsed.success || !["typing", "read"].includes(parsed.data.type)) return;
    const payload = JSON.stringify(parsed.data);
    for (const peer of this.ctx.getWebSockets()) {
      if (peer !== socket) peer.send(payload);
    }
  }
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const webhookMatch = url.pathname.match(/^\/api\/channels\/([^/]+)\/([^/]+)\/webhook$/);
    if (request.method === "POST" && webhookMatch) {
      const channel = webhookMatch[1] ?? "";
      const integrationId = webhookMatch[2] ?? "";
      const { createChannelBot, isChatSdkChannel } =
        await import("./src/features/integrations/server/chat-sdk");
      if (!isChatSdkChannel(channel)) {
        return Response.json({ error: "Unknown channel." }, { status: 404 });
      }
      return runWithCloudflareRequestContext(request, env, ctx, async () => {
        const { getDb } = await import("./src/lib/db/client");
        const db = getDb();
        const integration = await db.query.integration.findFirst({
          where: (fields, { and, eq }) =>
            and(eq(fields.id, integrationId), eq(fields.provider, channel.toUpperCase())),
          columns: { id: true, workspaceId: true, status: true, config: true },
        });
        const token = url.searchParams.get("token");
        const config = integration
          ? (JSON.parse(integration.config) as { webhookToken?: string })
          : {};
        if (!integration || integration.status !== "CONNECTED" || token !== config.webhookToken) {
          return Response.json({ error: "Webhook not found." }, { status: 404 });
        }
        const bot = createChannelBot({
          channel,
          namespace: env.CHAT_STATE,
          db,
          workspaceId: integration.workspaceId,
          integrationId: integration.id,
        });
        return bot.webhooks[channel](request, { waitUntil: (task) => ctx.waitUntil(task) });
      });
    }
    return nextWorker.fetch(request, env, ctx);
  },
  async queue(batch, env, ctx) {
    if (batch.queue === "widget-ingestion-jobs") {
      await processIngestionBatch(batch as MessageBatch<IngestionJob>, env, ctx);
      return;
    }

    console.error(JSON.stringify({ event: "queue.unknown", queue: batch.queue }));
    batch.retryAll({ delaySeconds: 300 });
  },
} satisfies ExportedHandler<CloudflareEnv, IngestionJob>;

// OpenNext cache exports, needed when cache Durable Objects are enabled later.
// @ts-ignore Generated by `opennextjs-cloudflare build`.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
export { ChatStateDO } from "chat-state-cloudflare-do";
