export const WIDGET_AGENT_RUN_TIMEOUT_MS = 55_000;
export const WIDGET_PREVIEW_RESPONSE_BUFFER_MS = 4_000;
export const WIDGET_PREVIEW_RESPONSE_TIMEOUT_MS =
  WIDGET_AGENT_RUN_TIMEOUT_MS + WIDGET_PREVIEW_RESPONSE_BUFFER_MS;
